### PR TITLE
Signature change for method logger_setup addressing #2

### PR DESCRIPTION
**Pull request by nischalhp**
Logger setup now takes arguments logger_name, env_cfg, init_messages
With this signature we can support various default loggers setup and
logger setup provided by environment variables.

### CODE REVIEW

**Comment by nischalhp** [comment]
> @nischalhp I don't like the fact that now the os.getenv is external to the library. In my opinion it should be impossible to use reconplogger in a way that it prevents re-configuring the logger via environment variables. So, I would propose that the signature be `def logger_setup(logger_name='plain_logger', config=None, env_prefix='LOGGER', init_messages=False)`. The function would setup the logger using `logger_name` and `config` as given. But if the environment variables `{env_prefix}_NAME` and/or `{env_prefix}_CFG` are set, then this would override the values given to `logger_setup`.

@mauvilsa - What would the config option in this signature do? I am little confused with the method signature now with env_prefix in the loop. Could you elaborate a bit more on the same?

**Comment by mauvilsa** [comment]
@nischalhp the config option could receive either a configuration string or a path to a configuration file to setup the logging module. So, basically people could give both a `logger_name` and a `config` to use as default for logging by their software. If the environment variables are set, then both of these would be overridden.

**Comment by nischalhp** [comment]
@mauvilsa  please take a look at this :)

**Comment by mauvilsa** [comment]
@nischalhp Took me a while to figure out why the unit tests were failing. Turns out that by default `logging.config.dictConfig` disables existing loggers, and if a logger that already exists gets reconfigured, it will remain disabled. In the unit tests the loggers get configured multiple times so at some point got to a test while the logger being tested was disabled. Added a line of code so that loggers are never disabled when using reconplogger. Don't understand why there is this behavior anyway.

While I was figuring out the problem I ended up making a bunch of changes. Will comment in a bit.

**Comment by mauvilsa** [comment]
@nischalhp look at the comment above from codecov. That is cool!

**Pull request merged**
